image: node:10.7.0

pipelines:
  default:
  - step:
       name: Build
       script:
           - npm install
           - npm run build
  branches:
    "{staging-2-0,pre-prod-2-0}":
    - step:
          name: Build and Test
          script:
            - npm install
            - git rm -r publish/*
            - npm run publish
            - echo "Generated new publish files"
            - git add --force publish/*
            - git add --force docs/*
            - git commit -m "[skip ci] Add publish files"
            - git push
