image: node:10.7.0

pipelines:
  default:
  - step:
       name: Build and Test
       script:
         - echo "Default"
  branches:
    development-1:
    - step:
          name: Build
          script:
          - npm install
          - npm run publish
    staging-1:
    - step:
          name: Build and Test
          script:
            - npm install
            - git rm -r publish/*
            - npm run publish
            - echo "Generated new publish files"
            - git add --force publish/*
            - git add --force docs/*
            - git commit -m "[skip ci] Add publish files"
            - git push
